package com.klarfinance.app.data.repository

import com.google.firebase.messaging.FirebaseMessaging
import com.klarfinance.app.core.network.ApiService
import com.klarfinance.app.core.network.NetworkUnavailableException
import com.klarfinance.app.core.session.SecureTokenStore
import com.klarfinance.app.core.session.SessionManager
import com.klarfinance.app.data.dto.ChangePasswordRequestDto
import com.klarfinance.app.data.dto.FcmTokenRequestDto
import com.klarfinance.app.data.dto.LoginRequestDto
import com.klarfinance.app.data.dto.LoginResponseDataDto
import com.klarfinance.app.data.dto.ProfileResponseDto
import com.klarfinance.app.data.dto.RefreshTokenRequestDto
import com.klarfinance.app.data.dto.RegisterResponseDataDto
import com.klarfinance.app.data.dto.RequestOtpRequestDto
import com.klarfinance.app.data.dto.VerifyOtpRequestDto
import com.klarfinance.app.data.dto.VerifyPasswordRequestDto
import com.klarfinance.app.data.local.LoanHistoryDao
import com.klarfinance.app.data.local.ProfileDao
import com.klarfinance.app.data.local.ProfileEntity
import com.klarfinance.app.data.local.ReferralSummaryDao
import com.klarfinance.app.data.local.TransjakartaTicketDao
import com.klarfinance.app.domain.model.AccountProfile
import com.klarfinance.app.domain.model.AccountState
import com.klarfinance.app.domain.model.Cached
import com.klarfinance.app.domain.model.LoginResult
import com.klarfinance.app.domain.model.RegisterResult
import com.klarfinance.app.domain.repository.AuthRepository
import kotlinx.coroutines.suspendCancellableCoroutine
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.MultipartBody
import okhttp3.RequestBody.Companion.toRequestBody
import javax.inject.Inject
import kotlin.coroutines.resume

class AuthRepositoryImpl @Inject constructor(
    private val apiService: ApiService,
    private val sessionManager: SessionManager,
    private val secureTokenStore: SecureTokenStore,
    private val profileDao: ProfileDao,
    private val loanHistoryDao: LoanHistoryDao,
    private val transjakartaTicketDao: TransjakartaTicketDao,
    private val referralSummaryDao: ReferralSummaryDao,
) : AuthRepository {

    override suspend fun requestOtp(phone: String): Result<Unit> = runCatching {
        apiService.post<Unit, RequestOtpRequestDto>("api/v1/auth/request-otp", RequestOtpRequestDto(phone))
        Unit
    }

    override suspend fun verifyOtp(phone: String, otp: String): Result<Unit> = runCatching {
        apiService.post<Unit, VerifyOtpRequestDto>("api/v1/auth/verify-otp", VerifyOtpRequestDto(phone, otp))
        Unit
    }

    override suspend fun isPhoneRegistered(phone: String): Result<Boolean> = runCatching {
        apiService.get<Boolean>("api/v1/auth/check-phone", params = mapOf("phone" to phone)).data ?: false
    }

    /** Reuses the same `/internal/auth/login` endpoint the staff apps (webadmin/frontend) call -
     * it's generic by identity+password regardless of role, see kotlin-nasabah-app knowledge. */
    override suspend fun login(identity: String, password: String): Result<LoginResult> = runCatching {
        val response = apiService.post<LoginResponseDataDto, LoginRequestDto>(
            "api/v1/internal/auth/login",
            LoginRequestDto(identity, password),
        )
        val data = response.data ?: throw IllegalStateException("Unexpected response from server")
        data.accessToken?.let { access -> sessionManager.save(access, data.refreshToken) }
        // Persisted unconditionally (not just when "Sidik Jari" is enabled) so EVERY logged-in
        // user survives an app restart - SecureTokenStore.isAppLockEnabled() is what decides
        // whether SplashViewModel gates the redemption behind a biometric prompt, not whether
        // the token is stored at all.
        data.refreshToken?.let { refresh -> secureTokenStore.saveRefreshToken(refresh) }
        syncFcmToken()
        LoginResult(
            identity = data.userProfile?.identity,
            name = data.userProfile?.name,
            accountState = AccountState.fromBackend(data.accountStatus),
        )
    }

    override suspend fun updateFcmToken(token: String): Result<Unit> = runCatching {
        apiService.patch<Unit, FcmTokenRequestDto>("api/v1/internal/auth/fcm-token", FcmTokenRequestDto(token))
        Unit
    }

    /** Best-effort, called right after a session is established (login/auto-login-after-register)
     * - the token itself is usually already generated by the time this runs (FCM generates it on
     * first app launch, independent of login state), this is just the first point we HAVE a
     * session to attach it to server-side. Deliberately swallows failure (via runCatching, result
     * discarded) - a push-notification token sync should never fail the login flow itself. */
    private suspend fun syncFcmToken() {
        runCatching {
            val token = suspendCancellableCoroutine<String?> { continuation ->
                FirebaseMessaging.getInstance().token.addOnCompleteListener { task ->
                    if (continuation.isActive) continuation.resume(if (task.isSuccessful) task.result else null)
                }
            }
            if (token != null) updateFcmToken(token)
        }
    }

    override suspend fun getProfile(): Result<Cached<AccountProfile>> {
        val networkResult = runCatching {
            val response = apiService.get<ProfileResponseDto>("api/v1/internal/auth/profile")
            val data = response.data ?: throw IllegalStateException("Unexpected response from server")
            AccountProfile(
                name = data.name,
                phone = data.noHp,
                role = data.role,
                dob = data.dob,
                email = data.email,
                emailVerified = data.emailVerified,
                accountState = AccountState.fromBackend(data.accountStatus),
            )
        }
        networkResult.onSuccess { profile ->
            profileDao.upsert(
                ProfileEntity(
                    name = profile.name,
                    phone = profile.phone,
                    role = profile.role,
                    dob = profile.dob,
                    email = profile.email,
                    emailVerified = profile.emailVerified,
                    accountState = profile.accountState.name,
                    cachedAtMillis = System.currentTimeMillis(),
                ),
            )
            return Result.success(Cached(profile, isFromCache = false))
        }

        val error = networkResult.exceptionOrNull()
        if (error is NetworkUnavailableException) {
            profileDao.get()?.let { cached ->
                return Result.success(
                    Cached(
                        AccountProfile(
                            name = cached.name,
                            phone = cached.phone,
                            role = cached.role,
                            dob = cached.dob,
                            email = cached.email,
                            emailVerified = cached.emailVerified,
                            accountState = AccountState.entries.find { it.name == cached.accountState }
                                ?: AccountState.GUEST,
                        ),
                        isFromCache = true,
                    ),
                )
            }
        }
        return Result.failure(error ?: IllegalStateException("Unknown error"))
    }

    override suspend fun changePassword(oldPassword: String, newPassword: String): Result<Unit> = runCatching {
        apiService.patch<Unit, ChangePasswordRequestDto>(
            "api/v1/internal/auth/change-password",
            ChangePasswordRequestDto(oldPassword, newPassword),
        )
        Unit
    }

    override suspend fun verifyPassword(password: String): Result<Unit> = runCatching {
        apiService.post<Unit, VerifyPasswordRequestDto>(
            "api/v1/internal/auth/verify-password",
            VerifyPasswordRequestDto(password),
        )
        Unit
    }

    /** Always clears the local session regardless of whether the server call succeeds -
     * a network hiccup shouldn't be able to strand the user in a logged-in-looking state.
     * Also drops the persisted refresh token - backend logout deletes all of the user's
     * tokens, so it would fail on the next cold-start restore anyway; clearing it here just
     * avoids a dead attempt. Also clears the offline caches (profile/loan history/Transjakarta
     * tickets) - a shared/lost device shouldn't keep showing the previous user's data to
     * whoever opens the app next while offline. */
    override suspend fun logout(): Result<Unit> {
        val result = runCatching {
            apiService.post<Unit>("api/v1/internal/auth/logout")
            Unit
        }
        sessionManager.clear()
        secureTokenStore.clear()
        profileDao.clear()
        loanHistoryDao.clear()
        transjakartaTicketDao.clear()
        referralSummaryDao.clear()
        return result
    }

    override suspend fun refreshSession(refreshToken: String): Result<AccountState> = runCatching {
        val response = apiService.post<LoginResponseDataDto, RefreshTokenRequestDto>(
            "api/v1/internal/auth/refresh",
            RefreshTokenRequestDto(refreshToken),
        )
        val data = response.data ?: throw IllegalStateException("Unexpected response from server")
        val access = data.accessToken ?: throw IllegalStateException("Unexpected response from server")
        val refresh = data.refreshToken ?: throw IllegalStateException("Unexpected response from server")
        sessionManager.save(access, refresh)
        // The backend rotates the refresh token on every redemption (single-use) - the stored
        // copy must be updated to the new one or the NEXT cold start would fail.
        secureTokenStore.saveRefreshToken(refresh)
        AccountState.fromBackend(data.accountStatus)
    }

    override suspend fun register(
        phone: String,
        nik: String,
        name: String,
        email: String,
        address: String,
        dob: String,
        villageId: Long,
        password: String,
        referralCode: String,
        fotoKtp: MultipartBody.Part,
        fotoKyc: MultipartBody.Part,
        pinjolApps: List<String>,
        bankApps: List<String>,
    ): Result<RegisterResult> = runCatching {
        val textMediaType = "text/plain".toMediaType()
        fun part(name: String, value: String) =
            MultipartBody.Part.createFormData(name, null, value.toRequestBody(textMediaType))

        val multipartBody = MultipartBody.Builder()
            .setType(MultipartBody.FORM)
            .addPart(part("phone", phone))
            .addPart(part("nik", nik))
            .addPart(part("name", name))
            .addPart(part("email", email))
            .addPart(part("address", address))
            .addPart(part("dob", dob))
            .addPart(part("villageId", villageId.toString()))
            .addPart(part("password", password))
            .apply { if (referralCode.isNotBlank()) addPart(part("referralCode", referralCode)) }
            // Backend CustomerRegisterRequest.pinjolApps/bankApps adalah List<String>, di-bind
            // lewat @ModelAttribute (WebDataBinder) - beberapa part dengan NAMA SAMA otomatis
            // ke-collect jadi satu List (satu part per item, bukan digabung koma di satu part).
            .apply { pinjolApps.forEach { addPart(part("pinjolApps", it)) } }
            .apply { bankApps.forEach { addPart(part("bankApps", it)) } }
            .addPart(fotoKtp)
            .addPart(fotoKyc)
            .build()

        val response = apiService.postMultipart<RegisterResponseDataDto>("api/v1/auth/register", multipartBody)
        val data = response.data
        RegisterResult(
            identity = data?.identity,
            applicationStatus = data?.applicationStatus,
            suggestedLimit = data?.suggestedLimit,
            message = data?.message,
        )
    }
}
